"""Decide whether and how to inject shell integration at spawn time.

The terminal swaps a plain `[bash]` argv for
`[bash, --rcfile, <wrapper>]`, where the generated wrapper sources the
user's ~/.bashrc first and then the shipped integration snippet. The
snippet itself never touches ~/.bashrc, so users on other setups can
source it manually. Every decision here fails open: when anything is
off, missing, or unexpected, the original argv is returned untouched.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

KILL_SWITCH_ENV = "AGENT_TERMINAL_NO_INTEGRATION"
_WRAPPER_NAME = "agent-terminal-rcfile.bash"


def snippet_path() -> str:
    return str(Path(__file__).resolve().parent / "shell"
               / "agent-terminal.bash")


def wrapper_content(snippet: str) -> str:
    return ("# Generated by Agent Terminal; do not edit.\n"
            "[ -f \"$HOME/.bashrc\" ] && . \"$HOME/.bashrc\"\n"
            f". '{snippet}'\n")


def default_wrapper_dir(env=None) -> str:
    env = os.environ if env is None else env
    base = env.get("XDG_RUNTIME_DIR") or tempfile.gettempdir()
    return os.path.join(base, "agent-terminal")


def should_wrap(argv, env, assistant, *, explicit_command=False) -> bool:
    """The full decision table for injecting the rcfile wrapper."""
    if assistant is None or not assistant.enabled:
        return False
    if not assistant.shell_integration:
        return False
    if explicit_command:
        return False
    if env.get(KILL_SWITCH_ENV):
        return False
    if len(argv) != 1:
        return False
    if os.path.basename(argv[0]) != "bash":
        return False
    return True


def ensure_wrapper(wrapper_dir: str, snippet: str) -> str:
    """Write the wrapper rcfile if missing or stale; returns its path."""
    path = Path(wrapper_dir) / _WRAPPER_NAME
    content = wrapper_content(snippet)
    try:
        if path.read_text(encoding="utf-8") == content:
            return str(path)
    except OSError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return str(path)


def wrap_argv(argv, env, assistant, *, explicit_command=False,
              wrapper_dir=None, snippet=None) -> list[str]:
    """Return the injected argv, or the original argv on any obstacle."""
    argv = list(argv)
    try:
        if not should_wrap(argv, env, assistant,
                           explicit_command=explicit_command):
            return argv
        snippet = snippet or snippet_path()
        if not os.path.isfile(snippet):
            return argv
        wrapper = ensure_wrapper(wrapper_dir or default_wrapper_dir(env),
                                 snippet)
        return [argv[0], "--rcfile", wrapper]
    except OSError:
        return argv
